apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: micuemerson/springboot-k8s-autoscaling-workloads:v1.0.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m" 
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"